name: ci

on: [push]

permissions:
  contents: read

env:
  NODE_VERSION: "22.11.0"
  NODE_ENV: "ci"

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'

  ci-lambda:
    runs-on: ubuntu-latest
    needs: setup-node
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./lambda-scraper
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Build code
        run: yarn build

  ci-deployer:
    runs-on: ubuntu-latest
    needs: setup-node
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./deployer
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Build code
        run: yarn build

  ci-front:
    runs-on: ubuntu-latest
    needs: setup-node
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./energylandia-stats
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Build code
        run: yarn build